instructions = {
    16: "ADD",
    17: "SUB",
    18: "MUL",
    19: "DIV",
    1:  "MOV",
    22: "MVI",
    0:  "ADR",
    2:  "STR",
    3:  "STRB",
    4:  "LDR",
    5:  "LDRB",
    7:  "B",
    21: "BL",
    6:  "BX",
    8:  "BNE",
    9:  "BGT",
    10: "BLT",
    11: "BEQ",
    12: "CMP",
    13: "AND",
    14: "ORR",
    15: 'EOR',
    20:  "SWI"
}