SYSTEM_CODES = {
    0: "Success",
    1: "Operation completed successfully",
    100: "Unknown error occurred",
    101: "No program loaded",
    102: "Memory allocation error",
    103: "Invalid instruction",
    104: "Division by zero",
    105: "Invalid memory access",
    106: "Stack overflow",
    107: "Stack underflow",
    108: "Invalid register",
    109: "File not found",
    110: "Out of bounds memory access",
}